server:
  port: 8080

swagger:
  # 部署时间yyyy-MM-dd HH:mm:ss
  publishDate: false

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis相关配置
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 1234
