server:
  port: 8080

swagger:
  # 部署时间yyyy-MM-dd HH:mm:ss
  publishDate:
  enable: true

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis相关配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 1234

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl